importerApp/urls.py
from django.urls import path
from importerApp.views import ReadDataFileViewSet, uploadfile

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"read-file", ReadDataFileViewSet)


urlpatterns = [path("", uploadfile, name="uploadfile")]

project_django_importer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views
from importerApp.urls import router


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("importerApp.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "api/token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

importerApp/models.py
from django.db import models


class UploadFile(models.Model):
    file_path = models.FileField(upload_to="uploaded")
    created_date = models.DateTimeField(auto_now_add=True)


class ReadDataFile(models.Model):
    region = models.CharField(max_length=45)
    order_date = models.DateField()
    order_id = models.IntegerField()
    total = models.FloatField()

importerApp/views.py
import datetime

import numpy as np
import pandas as pd
import pathlib
from django.shortcuts import render

from importerApp.models import ReadDataFile, UploadFile

from rest_framework import viewsets
from importerApp.serializers import ReadDataFileSerializer


class ReadDataFileViewSet(viewsets.ModelViewSet):
    queryset = ReadDataFile.objects.all()
    serializer_class = ReadDataFileSerializer

    # permission_classes = (permissions.IsAuthenticated,)


def uploadfile(request):
    if request.method == "POST":
        file_uploaded = request.FILES["file_path"]
        # extension = pathlib.Path(file_uploaded.name).suffix
        upfile = UploadFile.objects.create(file_path=file_uploaded)
        process_data(upfile.file_path.name)
    return render(
        request,
        "uploadfile.html",
        context={
            "readDataFile": ReadDataFile.objects.all(),
        },
    )


def process_data(uploadedfile):
    data = extract_file(uploadedfile)
    data = clean_data(data)
    save_data(data)


def extract_file(filename):
    csv_data = pd.read_csv("media/" + filename)
    return csv_data


def clean_data(csv_data):
    for item in range(csv_data["Order Date"].size):
        try:
            csv_data.at[item, "Order Date"] = pd.to_datetime(
                csv_data["Order Date"].iloc[item]
            ).date()
        except ValueError:
            csv_data.at[item, "Order Date"] = np.NaN
    return csv_data.dropna().reset_index(drop=True)


def save_data(data):
    for row in data.itertuples(index=False):
        ReadDataFile.objects.create(
            region=row[0],
            order_date=row[1],
            order_id=row[2],
            total=row[3],
        )

templates/uploadfile.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" rel="stylesheet">

        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>

    </head>
    <body>
        <div class='container' >
            <div class="card">
                <div class="card-body">
                    <h1>Upload File Here:</h1>
                    <form action="{% url 'uploadfile' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="id_file_path" class="form-label">Please only CSV and XLSX</label>
                            <input class="form-control" type="file" name= "file_path" id="id_file_path" required="">
                        </div>
                        <input type="submit" class="btn btn-success" role="button" value="Save" name="_save"></input>
                    </form>
                </div>
            </div>

            <div class="container mt-5">
                <table class="table">
                <thead>
                    <tr>
                        <th>Region</th>
                        <th>Order Date</th>
                        <th>Order Id</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for element in readDataFile %}
                        <tr>
                            <td scope="row">{{element.region}}</td>
                            <td>{{element.order_date}}</td>
                            <td>{{element.order_id}}</td>
                            <td>{{element.total}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>


        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

        <script>$(document).ready(function () {
            $('.table').DataTable();
            });</script>

        <script src = "https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" ></script>
        <script src = "https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" ></script>


    </body>
</html>